/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Registry */
        get: operations["get_registry_api_config_registry_get"];
        /** Put Registry */
        put: operations["put_registry_api_config_registry_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/registry/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Registry Csv */
        get: operations["export_registry_csv_api_config_registry_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/registry/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Registry */
        post: operations["import_registry_api_config_registry_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/registry/import.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Registry Csv */
        post: operations["import_registry_csv_api_config_registry_import_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rules */
        get: operations["get_rules_api_config_rules_get"];
        /** Put Rules */
        put: operations["put_rules_api_config_rules_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Targets */
        get: operations["get_targets_api_config_targets_get"];
        /** Put Targets */
        put: operations["put_targets_api_config_targets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/first-seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get First Seen */
        get: operations["get_first_seen_api_first_seen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Active Jobs */
        get: operations["list_active_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/known-fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Known Fonts */
        get: operations["known_fonts_api_known_fonts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Proof */
        post: operations["upload_proof_api_registry_proof_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/proof/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proof */
        get: operations["get_proof_api_registry_proof__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Diff */
        get: operations["get_run_diff_api_runs__run_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run Csv */
        get: operations["export_run_csv_api_runs__run_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Scan */
        post: operations["start_scan_api_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Estimate */
        get: operations["scan_estimate_api_scan_estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedules */
        get: operations["get_schedules_api_schedules_get"];
        put?: never;
        /** Create Schedule Endpoint */
        post: operations["create_schedule_endpoint_api_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Schedule Endpoint */
        delete: operations["delete_schedule_endpoint_api_schedules__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspace Backups */
        get: operations["list_workspace_backups_api_workspace_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/backups/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_workspace_backups__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Workspace */
        get: operations["export_workspace_api_workspace_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Workspace */
        post: operations["import_workspace_api_workspace_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/restore/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup_api_workspace_restore__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot Workspace */
        post: operations["snapshot_workspace_api_workspace_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackupInfo */
        BackupInfo: {
            /** Created At */
            created_at: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Body_upload_proof_api_registry_proof_post */
        Body_upload_proof_api_registry_proof_post: {
            /** File */
            file: string;
        };
        /**
         * DiffResult
         * @description The difference between two runs, over findings that need action.
         */
        DiffResult: {
            /** Changed */
            changed?: components["schemas"]["FindingDelta"][];
            /** New Findings */
            new_findings?: components["schemas"]["Finding"][];
            /** Resolved Findings */
            resolved_findings?: components["schemas"]["Finding"][];
            /**
             * Unchanged Count
             * @default 0
             */
            unchanged_count: number;
        };
        /**
         * DomainFont
         * @description A font used on one domain, with how it was embedded and the hosts it was seen on.
         */
        DomainFont: {
            /** Assets */
            assets?: components["schemas"]["HostAsset"][];
            /** Embeddings */
            embeddings?: components["schemas"]["EmbeddingMethod"][];
            /** Family */
            family: string;
            /** Formats */
            formats?: components["schemas"]["FontFormat"][];
            /** Hosts */
            hosts?: string[];
            /**
             * License Reason
             * @default
             */
            license_reason: string;
            /** @default needs_check */
            license_verdict: components["schemas"]["LicenseVerdict"];
            /** Owner */
            owner?: string | null;
            /** @default not_applicable */
            privacy: components["schemas"]["PrivacyClass"];
        };
        /**
         * DomainReport
         * @description The domain-centric view of a scan: one target domain and what was found on it.
         */
        DomainReport: {
            /** Domain */
            domain: string;
            /** Fonts */
            fonts?: components["schemas"]["DomainFont"][];
            /**
             * Is Live
             * @default false
             */
            is_live: boolean;
            /** Live Hosts */
            live_hosts?: string[];
            /**
             * Pages Scanned
             * @default 0
             */
            pages_scanned: number;
            /** Subdomains */
            subdomains?: string[];
        };
        /**
         * EmbeddingMethod
         * @description How a font is delivered to the page.
         * @enum {string}
         */
        EmbeddingMethod: "self_hosted" | "google_fonts" | "adobe_fonts" | "monotype" | "other_cdn" | "system" | "unknown";
        /**
         * FamilySpec
         * @description Match a font by family name: contains every substring in `contains_all`
         *     (case-insensitive) and none in `excludes`. Empty `contains_all` never matches.
         */
        FamilySpec: {
            /** Contains All */
            contains_all?: string[];
            /** Excludes */
            excludes?: string[];
        };
        /**
         * Finding
         * @description A classified font identity: the unit of a report (ADR 0003, deterministic).
         */
        Finding: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Domains */
            domains?: string[];
            /** Embeddings */
            embeddings?: components["schemas"]["EmbeddingMethod"][];
            /** Evidence Notes */
            evidence_notes?: string[];
            /** Example Urls */
            example_urls?: string[];
            /** Family */
            family: string;
            /**
             * Family Group
             * @default
             */
            family_group: string;
            /** Formats */
            formats?: components["schemas"]["FontFormat"][];
            /**
             * License Reason
             * @default
             */
            license_reason: string;
            /** @default needs_check */
            license_verdict: components["schemas"]["LicenseVerdict"];
            metadata?: components["schemas"]["FontMetadata"] | null;
            /** Owner */
            owner?: string | null;
            /**
             * Page Count
             * @default 0
             */
            page_count: number;
            /** @default not_applicable */
            privacy: components["schemas"]["PrivacyClass"];
            /**
             * Registry Match
             * @default false
             */
            registry_match: boolean;
        };
        /**
         * FindingDelta
         * @description A finding present in both runs whose verdict or domain spread changed.
         */
        FindingDelta: {
            /** Family */
            family: string;
            /** New Domains */
            new_domains?: string[];
            new_verdict: components["schemas"]["LicenseVerdict"];
            /** Old Domains */
            old_domains?: string[];
            old_verdict: components["schemas"]["LicenseVerdict"];
            /** Owner */
            owner?: string | null;
        };
        /** FirstSeen */
        FirstSeen: {
            /** Domain */
            domain: string;
            /** Family */
            family: string;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
        };
        /**
         * FontFormat
         * @description Web font file format.
         * @enum {string}
         */
        FontFormat: "woff2" | "woff" | "ttf" | "otf" | "eot" | "unknown";
        /**
         * FontMetadata
         * @description Fields read from a font file's `name` table (any may be missing/stripped).
         */
        FontMetadata: {
            /** Copyright */
            copyright?: string | null;
            /** Designer */
            designer?: string | null;
            /** Family Name */
            family_name?: string | null;
            /** Fs Type */
            fs_type?: number | null;
            /** License Description */
            license_description?: string | null;
            /** License Url */
            license_url?: string | null;
            /** Num Glyphs */
            num_glyphs?: number | null;
            /** Owner */
            owner?: string | null;
            /** Unique Id */
            unique_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HostAsset
         * @description The font-file URL(s) a font was served from on one host.
         */
        HostAsset: {
            /** Host */
            host: string;
            /** Urls */
            urls?: string[];
        };
        /** Job */
        Job: {
            /**
             * Current
             * @default 0
             */
            current: number;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Mode
             * @default real
             * @enum {string}
             */
            mode: "real" | "demo";
            /**
             * Phase
             * @default
             */
            phase: string;
            /** Run Id */
            run_id?: string | null;
            /** @default running */
            status: components["schemas"]["JobStatus"];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "running" | "done" | "error";
        /** KnownFont */
        KnownFont: {
            /** Family */
            family: string;
            /** Owner */
            owner?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "detected" | "catalog";
        };
        /**
         * LicenseVerdict
         * @description Deterministic license classification (ADR 0003). Nuance lives in the reason.
         *
         *     OK          — no action needed: covered by a registry license, provably open,
         *                   or a system/fallback font (no license question).
         *     NEEDS_CHECK  — the honest default: no license on record and not provably open;
         *                   a human should look. Carries evidence notes explaining why.
         *     VIOLATION    — a definite lapse: a declared license expired or out of scope /
         *                   over max_domains, a paid tier served without cover, or a
         *                   self-host-prohibited font self-hosted without cover.
         * @enum {string}
         */
        LicenseVerdict: "ok" | "needs_check" | "violation";
        /**
         * PrivacyClass
         * @description How a font's delivery affects visitor privacy — the axis is independent of
         *     the license risk band. Third-party delivery (e.g. the Google Fonts API) sends
         *     each visitor's IP to that third party, a GDPR/RODO concern even when the font
         *     itself is freely licensed.
         * @enum {string}
         */
        PrivacyClass: "self_hosted" | "third_party_api" | "mixed" | "not_applicable" | "unknown";
        /** Registry */
        Registry: {
            /** Entries */
            entries?: components["schemas"]["RegistryEntry"][];
        };
        /** RegistryEntry */
        RegistryEntry: {
            /** Allowed Domains */
            allowed_domains?: string[];
            /** Family */
            family: string;
            /** Invoice Path */
            invoice_path?: string | null;
            /** License Type */
            license_type: string;
            /** Max Domains */
            max_domains?: number | null;
            /** Notes */
            notes?: string | null;
            /** Owner */
            owner: string;
            /** Proof Path */
            proof_path?: string | null;
            /** Valid Until */
            valid_until?: string | null;
        };
        /**
         * RegistryImportResult
         * @description Result of a registry import: the merged registry, per-row errors (CSV only),
         *     and how the merge changed what was already there — replacements are reported
         *     because an import can silently *loosen* an entry (e.g. drop its expiry).
         */
        RegistryImportResult: {
            /**
             * Added
             * @default 0
             */
            added: number;
            /** Errors */
            errors?: string[];
            registry: components["schemas"]["Registry"];
            /**
             * Replaced
             * @default 0
             */
            replaced: number;
        };
        /**
         * RulesConfig
         * @description Classification data for the verdict engine (editable without touching code).
         */
        RulesConfig: {
            /** Desktop Formats */
            desktop_formats?: string[];
            /** Free Owners */
            free_owners?: string[];
            /** Open Families */
            open_families?: components["schemas"]["FamilySpec"][];
            /** Open License Patterns */
            open_license_patterns?: string[];
            /** Paid Cdns */
            paid_cdns?: string[];
            /** Paid Tier Families */
            paid_tier_families?: components["schemas"]["FamilySpec"][];
            self_host_prohibited?: components["schemas"]["SelfHostProhibited"];
            /**
             * Subset Max Glyphs
             * @default 256
             */
            subset_max_glyphs: number;
        };
        /** RunMeta */
        RunMeta: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Id */
            id: string;
            summary: components["schemas"]["RunSummary"];
        };
        /**
         * RunReport
         * @description A complete scan run: the JSON source of truth that every output derives from.
         */
        RunReport: {
            /** Domains */
            domains?: components["schemas"]["DomainReport"][];
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Schema Version
             * @default 10
             */
            schema_version: number;
            summary: components["schemas"]["RunSummary"];
        };
        /**
         * RunSummary
         * @description Headline counts for one scan run.
         */
        RunSummary: {
            /** By Privacy */
            by_privacy?: {
                [key: string]: number;
            };
            /** By Verdict */
            by_verdict?: {
                [key: string]: number;
            };
            /**
             * Needs Action
             * @default 0
             */
            needs_action: number;
            /**
             * Total Findings
             * @default 0
             */
            total_findings: number;
        };
        /** ScanEstimate */
        ScanEstimate: {
            /** Based On Runs */
            based_on_runs: number;
            /** Eta Seconds */
            eta_seconds: number | null;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Discover Subdomains
             * @default false
             */
            discover_subdomains: boolean;
            /** Max Pages Per Domain */
            max_pages_per_domain?: number | null;
            /**
             * Mode
             * @default demo
             * @enum {string}
             */
            mode: "real" | "demo";
        };
        /** ScanStarted */
        ScanStarted: {
            /** Job Id */
            job_id: string;
        };
        /** ScheduleInfo */
        ScheduleInfo: {
            /** Name */
            name: string;
            /** Next Run */
            next_run?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ScheduleSpec */
        ScheduleSpec: {
            /**
             * Day Of Week
             * @default MON
             * @enum {string}
             */
            day_of_week: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
            /**
             * Frequency
             * @default weekly
             * @enum {string}
             */
            frequency: "daily" | "weekly";
            /**
             * Mode
             * @default real
             * @enum {string}
             */
            mode: "demo" | "real";
            /** Name */
            name: string;
            /**
             * Time
             * @default 06:00
             */
            time: string;
        };
        /** SelfHostProhibited */
        SelfHostProhibited: {
            /** Families */
            families?: string[];
            /** Owners */
            owners?: string[];
        };
        /** Target */
        Target: {
            /** Domain */
            domain: string;
            /** Subdomain Seeds */
            subdomain_seeds?: string[];
        };
        /** TargetsConfig */
        TargetsConfig: {
            /** Targets */
            targets?: components["schemas"]["Target"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_registry_api_config_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registry"];
                };
            };
        };
    };
    put_registry_api_config_registry_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_registry_csv_api_config_registry_export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_registry_api_config_registry_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_registry_csv_api_config_registry_import_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryImportResult"];
                };
            };
        };
    };
    get_rules_api_config_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesConfig"];
                };
            };
        };
    };
    put_rules_api_config_rules_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulesConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_targets_api_config_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetsConfig"];
                };
            };
        };
    };
    put_targets_api_config_targets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetsConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetsConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_first_seen_api_first_seen_get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirstSeen"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_active_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    known_fonts_api_known_fonts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnownFont"][];
                };
            };
        };
    };
    upload_proof_api_registry_proof_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_proof_api_registry_proof_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proof_api_registry_proof__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMeta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_diff_api_runs__run_id__diff_get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_csv_api_runs__run_id__export_csv_get: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_api_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_estimate_api_scan_estimate_get: {
        parameters: {
            query: {
                hosts: number;
                max_pages: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanEstimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedules_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"][];
                };
            };
        };
    };
    create_schedule_endpoint_api_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_endpoint_api_schedules__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspace_backups_api_workspace_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupInfo"][];
                };
            };
        };
    };
    download_backup_api_workspace_backups__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_workspace_api_workspace_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_workspace_api_workspace_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    restore_backup_api_workspace_restore__name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_workspace_api_workspace_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupInfo"];
                };
            };
        };
    };
}
